### ISSUE TITLE
Tied/fixed parameter and data worth analysis issues

### ISSUE THREAD

**Issue by katherbreen** [jtwhite79/pyemu#22]
I'm having difficulty running through the Schurexample_Freyberg.ipynb code with my own data.  The problems seem to be related to having tied or fixed parameters when calling 1) get_par_group_contribution() or 2) get_removed_obs_importance() on the Schur class.

Also, I have a general question.  I'm performing a data worth analysis on output data from a hydrologic model run in a data-poor system.  I have observation weights for all model predictions (time series of gw level) set to zero as in the example, but I find I get errors in the above functions if I don't have at least a few weights greater than zero...is this a quirk in the code or am I overlooking something fundamental?

Thank you for your time, and for a great, easy-to-implement tool!

[pyEMU_test_KBreen.zip](https://github.com/jtwhite79/pyemu/files/1070367/pyEMU_test_KBreen.zip)

**Comment by jtwhite79** [comment]
So it looks like you have no non-zero weight observations, which shouldn't be a problem from the implementation - you need to set the ``reset_zero_weight`` flag in the call to ``Schur.get_removed_obs_importance()`` (you also found a bug in this case where the forecasts were getting roped in as observations - just pushed a fix for this).  The ``reset_zero_weight`` flag will do just what it says, so then you are testing the value of each observation by removing it from all the others and recalculating forecast uncertainty. So essentially, you pretend to have all 80K observations, then see what happens when each one is removed. 

You might also want to check out  ``Schur.get_added_obs_importance()``, which tests the value of yet-to-be-collected observations by adding each one sequentially and recalculating forecast uncertainty.  Note this function also accepts the ``reset_zero_weight`` flag and you'll probably want to pass the ``base_obslist=[]`` (an empty list).  This one runs much faster in your case because there are no observations to start with, so it solves a case involving a single observation each time - this is a much smaller problem than ``get_removed_obs_importance()``, an 80K observation problem that is solved repeatedly.  

One more thing: since you don't have any non-zero weight observations, the forecast and parameter uncertainty reduction (prior vs posterior) will be zero (there is no "learning" from the observations).  That's why some of those charts look goofy. 

Also, if you set ``verbose=True`` in the ``Schur`` constructor, then you can see what's going on during the calcs, which I find pretty useful for finding problems...

As far as fixed parameters - they are excluded from the analyses because they are not in the Jacobian (they are implied to have zero uncertainty and are known perfectly).  However, if you want to test the value of knowing a parameter perfectly, then use the ```Schur.get_par_contribution()`` method.  Tied parameters are a little tricky conceptually in dataworth and uncertainty analysis - marking a parameter as "tied" implies it has a perfect correlation with another parameter (R^2 = 1.0), which is problematic from a computational standpoint.  I tend to think of tying parameters as a trick for parameter estimation to reduce computational burden, not for uncertainty and dataworth analyses. Does this make sense?

Looks like you are doing some interesting (possibly untested) things with dataworth so keep me posted if things seem strange.

**Comment by katherbreen** [comment]
Thank you for your suggestions, and for your thoughtful response.  Very helpful.

**Comment by katherbreen** [comment]
I tested your suggestions on a subset of data with no fixed parameters, but when I reapplied to the full data set the same issues persisted.  I removed tied parameters, but I'm still having trouble using fixed parameters with get_par_contribution(), which gives me the error pasted below.  I think the error is coming up because fixed parameters are mistakenly not being excluded from the analysis, correct?  If I remove fixed parameters the function will run.  Also, when I use get_removed_obs_importance() (with or without reset_zero_weight flag), I think the forecasts are still getting roped in as observations.  I recloned the pyemu files, but I'm still having problems unless I remove all fixed parameters and have a mix of observation weights.  I've found that I can get a good run if I set the "forecast" weights to zero, but all others to one.  It's an easy fix with a little text editing on my end.

Thank you again for your help, it is greatly appreciated.

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-79-f259574069ef> in <module>()
      1 # parameter contribution to forecast uncertainty
----> 2 df = la.get_par_group_contribution()
      3 df

C:\Users\Kathy_Breen\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyemu\sc.pyc in get_par_group_contribution(self)
    313         for grp,idxs in groups.items():
    314             pargrp_dict[grp] = list(par.loc[idxs,"parnme"])
--> 315         return self.get_par_contribution(pargrp_dict)
    316 
    317     def get_added_obs_importance(self,obslist_dict=None,base_obslist=None,

C:\Users\Kathy_Breen\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyemu\sc.pyc in get_par_contribution(self, parlist_dict)
    290             names.append(case_name)
    291             self.log("calculating contribution from: " + str(par_list) + '\n')
--> 292             case_prior,case_post = self.__contribution_from_parameters(par_list)
    293             self.log("calculating contribution from: " + str(par_list) + '\n')
    294             for forecast in case_prior.keys():

C:\Users\Kathy_Breen\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyemu\sc.pyc in __contribution_from_parameters(self, parameter_names)
    223         bprior,bpost = self.prior_prediction, self.posterior_prediction
    224         #get the prior and posterior for the conditioned case
--> 225         la_cond = self.get_conditional_instance(parameter_names)
    226         cprior,cpost = la_cond.prior_prediction, la_cond.posterior_prediction
    227         return cprior,cpost

C:\Users\Kathy_Breen\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyemu\sc.pyc in get_conditional_instance(self, parameter_names)
    235             parameter_names[iname] = name
    236             assert name in self.jco.col_names,\
--> 237                 "contribution parameter " + name + " not found jco"
    238         keep_names = []
    239         for name in self.jco.col_names:

AssertionError: contribution parameter [fixed parameter name] not found jco

**Comment by jtwhite79** [comment]
I think the issue with get_par_group_contribution() has been fixed in the develop branch.  line 314 of your code (above) has been replaced with a list comprehension that is only using parameter names that are in the jacobian.  

Can you elaborate or show some code/output for the get_removed_obs_importance() so I can understand the issue a little better?

**Comment by katherbreen** [comment]
No problem - below is an example of the error output
[pyEMU_test_KBreen.zip](https://github.com/jtwhite79/pyemu/files/1092730/pyEMU_test_KBreen.zip)

**Comment by katherbreen** [comment]
No problem - below is an example of the errors.  
[pyEMU_test_KBreen2.zip](https://github.com/jtwhite79/pyemu/files/1092748/pyEMU_test_KBreen2.zip)

**Comment by jtwhite79** [comment]
ok - I think found the problem.  Forecasts need to have zero weight in the control file (conceptually they shouldn't be used for history matching as they are "unknown).  A few of yours had non-zero weight that was causing issues in the data worth part for selecting weights to reset and then selecting the "conditional instance".  So now there is a check in the constructor routines that forecasts must have zero weight...hopefully this isn't too burdensome - I could be convinced to just reset the weights and issue a warning...all this is in the develop branch.  Let me know if its your further along

**Comment by katherbreen** [comment]
Thanks for catching that!  I think the fix is helpful.  I knew my first forecast weight was set to zero, so the problem wasn't obvious, but it's much clearer with the fix.

I'm still having trouble with get_par_group_contribution().  The function now throws an error message that the control file is not available, even when it is successfully loaded by the Schur class
[pyEMU_test_KBreen3.zip](https://github.com/jtwhite79/pyemu/files/1095976/pyEMU_test_KBreen3.zip)

**Comment by jtwhite79** [comment]
So I jumped the gun on checking for forecasts with non-zero weight - sometimes, the Pst instance isn't available during the __load_predictions() routine, so I made the forecast weight checking optional.  Just pushed a fix to develop

I would check this on your problem, but the jco you uploaded doesn't have the forecast names?  I can verify this fix if you post the jco and pst that were giving you trouble...

**Comment by katherbreen** [comment]
Sorry about that, I sent you the wrong jco - my mistake.  Thank you for checking into this.
[pyEMU_test_KBreen4.zip](https://github.com/jtwhite79/pyemu/files/1098242/pyEMU_test_KBreen4.zip)

**Comment by jtwhite79** [comment]
Looks to run to completion with the develop branch.  Let me know how it goes...

**Comment by katherbreen** [comment]
Yes, working for me now.  Thanks so much!
