### ISSUE TITLE
exe name in forward_run when automagically generated

### ISSUE THREAD

**Issue by mnfienen-usgs** [jtwhite79/pyemu#23]
Yo - 

For Freyberg example, trying to make the automagically generated PEST files use NWT instead of MF2005 for the exe_name in the forward_run.py script. Can't seem to force that, though. I tried implementing passing in an org_model_exe_name optional variable and setting it, but somehow it's getting overwritten. Check out the `PST_to_pyemu_to_Schur_Overview.ipynb` notebook.

**Comment by jtwhite79** [comment]
I'm having the same issue. It's because flopy isn't resetting the exe_name, only the version even if it finds nwt or upw. Dumb I know. I tried to patch the problem in flopy but since there are other names for exes (e.g. Modflow-nwt_X64.exe) it caused other things to break. I'm thinking I'll just refactor the pstfromflopy constructor to take the loaded flopy model instead of the nam file. That would force users to have a "working" model WRT flopy.  I think that is a better approach anyway, just more steps...

**Comment by mnfienen-usgs** [comment]
That's cool. I tried adding an option to pass through a variable `org_model_exe_name` to override it getting set by `flopy` load but didn't work. Also, having issues on Travis getting the commit up....

**Comment by jtwhite79** [comment]
refactored - ``PstFromFlopy`` accepts a ``model`` arg, which can be a ``flopy.modflow.Modflow`` instance and ``org_model_ws`` is optional (and is ignored).  The ``model`` arg can also be a ``str``, which is treated as a nam file name and ``org_model_ws`` is used to load the model.,
