### ISSUE TITLE
Minor edit in the function modflow_hob_to_instruction_file()

### ISSUE THREAD

**Issue by unbiasedmodeler** [jtwhite79/pyemu#31]
Hello,

 I'm using the notebook titled 'modflow_to_pest_like_a_boss' to build PEST++ files for a groundwater model (I'm working with a team from USGS-NMWSC) . On running the function pyemu.gw_utils.modflow_hob_to_instruction_file() in cell 4 of the notebook, I get an instruction file in which a typical line is:

l1 w w !i03j10.2!

 Since we're interested in reading the values in the first column in the freyberg.hob.out file titled 'SIMULATED EQUIVALENT', I changed a line in the pyEMU source code (in the script gw_utils.py, in the function modflow_hob_to_instruction_file(), line 69 - removed the two w's), so a typical line in the instruction file now reads:

l1 !i03j10.2!

 I think this change is necessary for the head observation file that I'm working with (which is exactly like the file freyberg.hob.out) - I'm not sure if this change is required for other head observation files as well, but I thought I'd bring it to your attention.

Thanks,

Rishi Jumani.

**Comment by jtwhite79** [comment]
Hey @unbiasedmodeler (great handle BTW!) - you are right, that is a bug.  Its been fixed in the develop branch.  

If you are interested in the "auto setup" stuff, please check out this notebook (on develop branch):
[https://github.com/jtwhite79/pyemu/blob/develop/examples/notest_MODFLOW_to_PEST_even_more_boss.ipynb](https://github.com/jtwhite79/pyemu/blob/develop/examples/notest_MODFLOW_to_PEST_even_more_boss.ipynb)
This is more up-to-date and uses the latest and (hopefully) greatest

**Comment by unbiasedmodeler** [comment]
Thanks, @jtwhite79 I'll look into using the even_more_boss notebook ;
