### ISSUE TITLE
pst_handler / #comments

### ISSUE THREAD

**Issue by cnicol-gwlogic** [jtwhite79/pyemu#32]
A minor, possibly me-specific issue in pst_handler: if suitable for broad use, can we please add comment='#' to pd.read_csv() in _read_df()? Pyemu bombs on reading a big pest control file I have which has comments throughout, marked modflow-style with #s.

Thanks a lot,
Chris.

**Comment by jtwhite79** [comment]
def wanna support comments in the control file!  Are your comments entire lines mixed in the ``DataFramed``'d sections or extra things at the end of the lines?  Can you upload you control file so I can add it to the tests?

**Comment by cnicol-gwlogic** [comment]
Awesome, thanks a lot. Comments are all end of line in my case, within the parameter and/or obs sections - I tested adding comment='#' to pd.read_csv() in _read_df() and it works fine with my file: 
[dualss_csgtrans_regwtsadj_v8_hp_dataworth_noregV3_base.zip](https://github.com/jtwhite79/pyemu/files/1805067/dualss_csgtrans_regwtsadj_v8_hp_dataworth_noregV3_base.zip)
I guess it might be safest to add a parameter for users' comment character in calls to Pst()?

**Comment by jtwhite79** [comment]
Thanks for the file.  I'll work on this - I was thinking it would be good to carry the comments through so that when you write a new control file it keeps them. This will take some more work but I think its important:  I'm planning to start using the comments at the end of the lines to store metadata like spatial and temporal things...

**Comment by cnicol-gwlogic** [comment]
Ah good point, hadn't thought about re-writes, but yeah esp for monster files like this it is a nice touch.

**Comment by jtwhite79** [comment]
Ok, I think I got this going on the develop branch.  By default, if comments are found during read, then they are repeated in a write.  Let me know what you think.

**Comment by cnicol-gwlogic** [comment]
That works great - thanks a lot for implementing so quickly. 

As an aside, I have noticed a couple of other issues with re-writes, probably quite specific to my setup. I'll have a stab at sorting them out in the next day or so and send you my suggested changes for consideration (let me know if that's not the easiest way to get these to you - I'm new to github).

Cheers,
Chris.

**Comment by jtwhite79** [comment]
I'm keen to hear any issues you have.  Any contributions are welcome - pull request would be best.

**Comment by JOPESTKIL** [comment]
BED BUGS INFESTATION SPREADS LIKE WILD FIRES......
What makes me to wonder is that Bedbugs do not fly, but they can move quickly over floors, walls, and ceilings infesting anywhere. Female bedbugs may lay hundreds of eggs, each of which is about the size of a speck of dust, over a lifetime.
Immature bedbugs, called nymphs, shed their skins five times before reaching maturity and require a meal of blood before each shedding. Under favorable conditions the bugs can develop fully in as little as a month and produce three or more generations per year.
Although they are a nuisance, they are not thought to transmit diseases. The bug menace. https://www.jopestkil.com/

**Comment by JOPESTKIL** [comment]
BED BUGS INFESTATION... 
What They Look Like: Flat oval body with six legs, about the size of an apple seed that can be either brown or reddish brown.Typical ‘Hood: Can be found around the world, but recent outbreaks have centered in the United States, Canada, the UK, and other parts of Europe. Bed bugs are found in environments where many people cycle through on a given day—this includes apartments, hostels and hotels, trains, buses, and dorm rooms. Some theorists suggest that recent bed bug outbreaks are due to an increase in international travel, since the bugs can easily hide in luggage, bags, clothing, or bedding.Home Headquarters: Unsurprisingly, these pests love to hang out in and around the bed. Bed bugs’ small, flat bodies allow them to hide quite easily in seams of mattresses, bed frames, headboards, other bedroom furniture, behind wallpaper, in clothing, or any other household clutter.Fave Snacks: Blood. Bed bugs can live for up to a year in between “meals.”Danger Zone: Bed bugs don’t transmit diseases and are not considered a public health hazard. Bites cause itching, and dealing with an infestation can cause anxiety and insomnia. In some cases, bites can trigger a serious allergic reaction, but this is fairly rare. https://www.jopestkil.com/
