### ISSUE TITLE
MonteCarlo Draw Assertion Error with Sparse Covariance

### ISSUE THREAD

**Issue by mnfienen** [jtwhite79/pyemu#57]
Seems that the MC draw method bombs on an assertion error when passing it a `Cov` object made with `pyemu.utils.helpers.sparse_geostatistical_prior_builder()`

Not sure if best bet is to change the assertion at 161 in `mc.py` so that rather then `assert isinstance(cov,Cov)` also asserts to allow `isinstance(cov,SparseMatrix)`?

Alternative would be to issue a specific error if `SparseMatrix` isn't supported.

**Comment by jtwhite79** [comment]
I think the issue is that if ``cov`` is ``SparseMatrix`` type, you need to call a different ``ParameterEnsemble`` draw method ( ``from_sparse_gaussian_draw()`` instead of ``from_gaussian_draw()``) under the hood in ``MonteCarlo.draw()``.  Its easy enough, just need to type-check the ``cov`` arg and then add a conditional later on to make the right draw call.

**Comment by jtwhite79** [comment]
FYI - there is also now support for ``ParameterEnsemble.from_triangular_draw()`` and ``ParameterEnsemble.from_mixed_draw()``, which allows you to combine (multivariate) gaussian, uniform, and triangular distributions for different parameters.  Probably want to refactor the ``MonteCarlo.draw()`` to use the mixed-draw type because it is more general.  So let's leave this issue open as a reminder...

**Comment by jwhite-usgs** [comment]
I'm preparing to remove the sparse covariance matrix stuff - it was an interim solution.  These days, we just draw par group by par group to avoid ever needed to form a huge covariance matrix.
