### ISSUE TITLE
PstFromFlopyModel creates template files with rows longer than 2000 characters

### ISSUE THREAD

**Issue by corcorf** [jtwhite79/pyemu#74]
As I understand it this is a problem for standard PEST. PEST++ seems to be managing ok, but I can't find positive confirmation in the manuals that the row length limit doesn't apply for PEST++.

Is there a way to reduce the parameter space width, to reduce the resulting width of the template files?

**Comment by jwhite-usgs** [comment]
The line length limit for PEST++ is 200k chars at the mo.  To make the template file line lengths shorter means we need to read/write arrays in wrapped format (barf!) Which is harder to deal with since we can't use `numpy.loadtxt()`.  This probably doable but would require some hacking...there is an effort underway to generalize the PstFromFlopy concept - I'll add the idea of wrapped array support to the list of possible options.  Sorry there's not an easy answer for this.

**Comment by corcorf** [comment]
That good to know about the limit for PEST++ - I doubt I'll be breaching that any time soon! In which case the only issue is that PESTCHEK etc gets upset about the `.tpl` files when they're too long and won't proceed to check the rest of the inputs. But I can get around that by editing the templates to remove extra spaces, re-running PESTCHEK to check everything else, and then reinstating the original (large) versions of the template files.
Ta much.
F
